/**
 * Elara Sovereign Studio — Icon Library
 *
 * A curated, categorised registry of icons for agents, tools, skills, models,
 * capabilities and user profiles. Everything in the app should pick icons from
 * here (by string name) so cards stay consistent and icons can be persisted in
 * a database as plain strings.
 */
import {
  Activity,
  Airplay,
  AlarmClock,
  Album,
  AlertTriangle,
  Anchor,
  Aperture,
  Archive,
  AreaChart,
  Atom,
  Award,
  Axe,
  BadgeCheck,
  BarChart3,
  Battery,
  Beaker,
  Bell,
  Binary,
  Bird,
  Blocks,
  Bluetooth,
  Bolt,
  Bomb,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Brain,
  BrainCircuit,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Cable,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Cast,
  Castle,
  Cctv,
  Check,
  CheckCircle2,
  ChefHat,
  Chrome,
  CircuitBoard,
  Clapperboard,
  Clock,
  Cloud,
  CloudCog,
  CloudLightning,
  Code2,
  Codepen,
  Cog,
  Coins,
  Command,
  Compass,
  Component,
  Container,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Crown,
  Database,
  DatabaseZap,
  Diamond,
  Dices,
  Disc3,
  Dna,
  DollarSign,
  Download,
  Drama,
  Droplet,
  Drum,
  Eye,
  Factory,
  Feather,
  FileCode2,
  FileJson,
  FileSearch,
  FileText,
  Filter,
  Fingerprint,
  Flame,
  FlaskConical,
  Focus,
  FolderTree,
  Forklift,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  GraduationCap,
  Grid3x3,
  Hammer,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  History,
  Home,
  Hourglass,
  IdCard,
  Image,
  Inbox,
  Infinity as InfinityIcon,
  Info,
  Joystick,
  Key,
  KeyRound,
  Keyboard,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Layout,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link2,
  ListChecks,
  Lock,
  LogIn,
  Magnet,
  Mail,
  MapPin,
  Medal,
  Megaphone,
  Merge,
  MessageSquare,
  Mic,
  Microscope,
  Milestone,
  Monitor,
  Moon,
  Mountain,
  Map as MapIcon,
  MousePointer2,
  Move3d,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  Orbit,
  Package,
  Palette,
  Paperclip,
  PartyPopper,
  PenTool,
  Percent,
  PieChart,
  PiggyBank,
  Pin,
  Pipette,
  Plane,
  Play,
  Plug,
  Podcast,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Radar,
  Radiation,
  Radio,
  Recycle,
  Regex,
  Repeat,
  Rocket,
  Route,
  Router,
  Rss,
  Ruler,
  Satellite,
  SatelliteDish,
  Scale,
  Scan,
  ScanFace,
  School,
  Scissors,
  ScrollText,
  Search,
  Send,
  Server,
  ServerCog,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  Shuffle,
  Sigma,
  Signal,
  Siren,
  Slack,
  Sliders,
  Smartphone,
  Snowflake,
  Sparkles,
  Speaker,
  Spline,
  Split,
  Sprout,
  Square,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Swords,
  Syringe,
  Table2,
  Tag,
  Target,
  Telescope,
  Terminal,
  TestTube2,
  Thermometer,
  Ticket,
  Timer,
  ToggleRight,
  Tornado,
  TrafficCone,
  Trash2,
  TreePine,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unplug,
  Upload,
  UserCog,
  UserRound,
  Users,
  Variable,
  Vault,
  Video,
  Voicemail,
  Wallet,
  Wand2,
  Waves,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  ZoomIn,
  type LucideIcon,
} from "lucide-react";

export type IconCategory =
  | "agents"
  | "intelligence"
  | "tools"
  | "code"
  | "data"
  | "infrastructure"
  | "security"
  | "analytics"
  | "communication"
  | "media"
  | "science"
  | "business"
  | "nature"
  | "symbols";

export const iconCategories: { id: IconCategory; label: string; hint: string }[] = [
  { id: "agents", label: "Agents", hint: "Autonomous workers & personas" },
  { id: "intelligence", label: "Intelligence", hint: "Models, reasoning, memory" },
  { id: "tools", label: "Tools", hint: "Skills, utilities, actions" },
  { id: "code", label: "Code", hint: "Repos, runtimes, pipelines" },
  { id: "data", label: "Data", hint: "Storage, knowledge, indexes" },
  { id: "infrastructure", label: "Infrastructure", hint: "Fleet, network, compute" },
  { id: "security", label: "Security", hint: "Policy, identity, governance" },
  { id: "analytics", label: "Analytics", hint: "Reporting, metrics, cost" },
  { id: "communication", label: "Communication", hint: "Chat, mail, signals" },
  { id: "media", label: "Media", hint: "Audio, video, imaging" },
  { id: "science", label: "Science", hint: "Research & experiments" },
  { id: "business", label: "Business", hint: "Org, finance, operations" },
  { id: "nature", label: "Nature", hint: "Organic & environment" },
  { id: "symbols", label: "Symbols", hint: "Marks, shapes, accents" },
];

const registry: Record<IconCategory, Record<string, LucideIcon>> = {
  agents: {
    bot: Bot,
    "brain-circuit": BrainCircuit,
    "user-round": UserRound,
    "user-cog": UserCog,
    users: Users,
    ghost: Ghost,
    crown: Crown,
    drama: Drama,
    "chef-hat": ChefHat,
    swords: Swords,
    "id-card": IdCard,
    "scan-face": ScanFace,
    fingerprint: Fingerprint,
    bird: Bird,
    "graduation-cap": GraduationCap,
    "party-popper": PartyPopper,
    joystick: Joystick,
  },
  intelligence: {
    brain: Brain,
    sparkles: Sparkles,
    atom: Atom,
    orbit: Orbit,
    "wand-2": Wand2,
    lightbulb: Lightbulb,
    telescope: Telescope,
    infinity: InfinityIcon,
    dna: Dna,
    "flask-conical": FlaskConical,
    sigma: Sigma,
    variable: Variable,
    binary: Binary,
    hexagon: Hexagon,
    focus: Focus,
    eye: Eye,
  },
  tools: {
    wrench: Wrench,
    hammer: Hammer,
    axe: Axe,
    puzzle: Puzzle,
    "pen-tool": PenTool,
    brush: Brush,
    scissors: Scissors,
    ruler: Ruler,
    magnet: Magnet,
    pipette: Pipette,
    sliders: Sliders,
    "toggle-right": ToggleRight,
    cog: Cog,
    "settings-2": Settings2,
    crop: Crop,
    stamp: Stamp,
    "life-buoy": LifeBuoy,
    filter: Filter,
  },
  code: {
    "code-2": Code2,
    terminal: Terminal,
    "file-code-2": FileCode2,
    "file-json": FileJson,
    "git-branch": GitBranch,
    "git-merge": GitMerge,
    "git-pull-request": GitPullRequest,
    "git-commit": GitCommitHorizontal,
    github: Github,
    codepen: Codepen,
    regex: Regex,
    workflow: Workflow,
    spline: Spline,
    split: Split,
    merge: Merge,
    repeat: Repeat,
    shuffle: Shuffle,
    command: Command,
    keyboard: Keyboard,
    webhook: Webhook,
    blocks: Blocks,
    component: Component,
  },
  data: {
    database: Database,
    "database-zap": DatabaseZap,
    "hard-drive": HardDrive,
    archive: Archive,
    "folder-tree": FolderTree,
    library: Library,
    "book-open": BookOpen,
    notebook: Notebook,
    "file-text": FileText,
    "file-search": FileSearch,
    "table-2": Table2,
    layers: Layers,
    boxes: Boxes,
    box: Box,
    package: Package,
    container: Container,
    vault: Vault,
    inbox: Inbox,
    bookmark: Bookmark,
    album: Album,
    "qr-code": QrCode,
    hash: Hash,
  },
  infrastructure: {
    server: Server,
    "server-cog": ServerCog,
    cpu: Cpu,
    network: Network,
    router: Router,
    cloud: Cloud,
    "cloud-cog": CloudCog,
    satellite: Satellite,
    "satellite-dish": SatelliteDish,
    radar: Radar,
    plug: Plug,
    unplug: Unplug,
    cable: Cable,
    wifi: Wifi,
    bluetooth: Bluetooth,
    signal: Signal,
    globe: Globe,
    factory: Factory,
    forklift: Forklift,
    monitor: Monitor,
    laptop: Laptop,
    smartphone: Smartphone,
    printer: Printer,
    battery: Battery,
    bolt: Bolt,
    zap: Zap,
    gauge: Gauge,
    timer: Timer,
    hourglass: Hourglass,
    route: Route,
  },
  security: {
    shield: Shield,
    "shield-check": ShieldCheck,
    "shield-alert": ShieldAlert,
    lock: Lock,
    key: Key,
    "key-round": KeyRound,
    "log-in": LogIn,
    scan: Scan,
    siren: Siren,
    bug: Bug,
    radiation: Radiation,
    bomb: Bomb,
    cctv: Cctv,
    "badge-check": BadgeCheck,
    scale: Scale,
    landmark: Landmark,
    "check-circle-2": CheckCircle2,
    "alert-triangle": AlertTriangle,
    "traffic-cone": TrafficCone,
  },
  analytics: {
    "bar-chart-3": BarChart3,
    "line-chart": LineChart,
    "pie-chart": PieChart,
    "area-chart": AreaChart,
    "trending-up": TrendingUp,
    activity: Activity,
    percent: Percent,
    calculator: Calculator,
    "grid-3x3": Grid3x3,
    "list-checks": ListChecks,
    milestone: Milestone,
    history: History,
    clock: Clock,
    calendar: Calendar,
    "scroll-text": ScrollText,
    "alarm-clock": AlarmClock,
  },
  communication: {
    "message-square": MessageSquare,
    mail: Mail,
    send: Send,
    megaphone: Megaphone,
    bell: Bell,
    rss: Rss,
    podcast: Podcast,
    radio: Radio,
    voicemail: Voicemail,
    "share-2": Share2,
    "link-2": Link2,
    paperclip: Paperclip,
    quote: Quote,
    newspaper: Newspaper,
    slack: Slack,
    languages: Languages,
  },
  media: {
    camera: Camera,
    video: Video,
    image: Image,
    mic: Mic,
    headphones: Headphones,
    speaker: Speaker,
    music: Music,
    "disc-3": Disc3,
    clapperboard: Clapperboard,
    tv: Tv,
    cast: Cast,
    airplay: Airplay,
    aperture: Aperture,
    palette: Palette,
    play: Play,
    "zoom-in": ZoomIn,
    drum: Drum,
    lamp: Lamp,
  },
  science: {
    microscope: Microscope,
    "test-tube-2": TestTube2,
    beaker: Beaker,
    syringe: Syringe,
    stethoscope: Stethoscope,
    "heart-pulse": HeartPulse,
    thermometer: Thermometer,
    circuit: CircuitBoard,
    "move-3d": Move3d,
    compass: Compass,
    navigation: Navigation,
    map: MapIcon,
    "map-pin": MapPin,
    crosshair: Crosshair,
    target: Target,
    "mouse-pointer-2": MousePointer2,
  },
  business: {
    briefcase: Briefcase,
    "building-2": Building2,
    store: Store,
    "shopping-bag": ShoppingBag,
    wallet: Wallet,
    coins: Coins,
    "dollar-sign": DollarSign,
    "credit-card": CreditCard,
    "piggy-bank": PiggyBank,
    ticket: Ticket,
    tag: Tag,
    trophy: Trophy,
    medal: Medal,
    award: Award,
    school: School,
    home: Home,
    truck: Truck,
    ship: Ship,
    plane: Plane,
    castle: Castle,
  },
  nature: {
    leaf: Leaf,
    sprout: Sprout,
    "tree-pine": TreePine,
    flame: Flame,
    droplet: Droplet,
    waves: Waves,
    snowflake: Snowflake,
    sun: Sun,
    moon: Moon,
    "cloud-lightning": CloudLightning,
    tornado: Tornado,
    mountain: Mountain,
    feather: Feather,
    umbrella: Umbrella,
    recycle: Recycle,
    anchor: Anchor,
    heart: Heart,
  },
  symbols: {
    gem: Gem,
    diamond: Diamond,
    star: Star,
    sparkle: Sparkles,
    hexagon2: Hexagon,
    triangle: Triangle,
    square: Square,
    circle: Disc3,
    rocket: Rocket,
    dices: Dices,
    gift: Gift,
    candy: Candy,
    cookie: Cookie,
    pin: Pin,
    check: Check,
    info: Info,
    copy: Copy,
    trash: Trash2,
    upload: Upload,
    download: Download,
    search: Search,
    layout: Layout,
    chrome: Chrome,
    "party-flag": Milestone,
  },
};

export type IconEntry = {
  name: string;
  category: IconCategory;
  Icon: LucideIcon;
  keywords: string;
};

export const iconLibrary: IconEntry[] = Object.entries(registry).flatMap(([category, set]) =>
  Object.entries(set).map(([name, Icon]) => ({
    name,
    category: category as IconCategory,
    Icon,
    keywords: `${name} ${category}`.toLowerCase(),
  })),
);

const byName = new Map(iconLibrary.map((entry) => [entry.name, entry]));

/** Resolve an icon by its library name; falls back to a neutral mark. */
export function getIcon(name?: string | null): LucideIcon {
  return (name && byName.get(name)?.Icon) || Hexagon;
}

export function iconsByCategory(category: IconCategory): IconEntry[] {
  return iconLibrary.filter((entry) => entry.category === category);
}

export function searchIcons(query: string, category?: IconCategory | "all"): IconEntry[] {
  const q = query.trim().toLowerCase();
  return iconLibrary.filter(
    (entry) =>
      (!category || category === "all" || entry.category === category) &&
      (!q || entry.keywords.includes(q)),
  );
}

export const iconCount = iconLibrary.length;
