/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppToolsRouteImport } from './routes/_app.tools'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppTelemetryRouteImport } from './routes/_app.telemetry'
import { Route as AppTargetsRouteImport } from './routes/_app.targets'
import { Route as AppSystemEngineRouteImport } from './routes/_app.system-engine'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPythonRouteImport } from './routes/_app.python'
import { Route as AppPoliciesRouteImport } from './routes/_app.policies'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppOrchestrationRouteImport } from './routes/_app.orchestration'
import { Route as AppModelsRouteImport } from './routes/_app.models'
import { Route as AppMiddlewareRouteImport } from './routes/_app.middleware'
import { Route as AppMetaForgeRouteImport } from './routes/_app.meta-forge'
import { Route as AppMcpRouteImport } from './routes/_app.mcp'
import { Route as AppLiveCallRouteImport } from './routes/_app.live-call'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppForgeRouteImport } from './routes/_app.forge'
import { Route as AppDebugRouteImport } from './routes/_app.debug'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCveRouteImport } from './routes/_app.cve'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCapabilitiesRouteImport } from './routes/_app.capabilities'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppAdaptersRouteImport } from './routes/_app.adapters'
import { Route as AppKnowledgeAliasesRouteImport } from './routes/_app.knowledge_.aliases'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemetryRoute = AppTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => AppRoute,
} as any)
const AppTargetsRoute = AppTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemEngineRoute = AppSystemEngineRouteImport.update({
  id: '/system-engine',
  path: '/system-engine',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPythonRoute = AppPythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppOrchestrationRoute = AppOrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppMiddlewareRoute = AppMiddlewareRouteImport.update({
  id: '/middleware',
  path: '/middleware',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaForgeRoute = AppMetaForgeRouteImport.update({
  id: '/meta-forge',
  path: '/meta-forge',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveCallRoute = AppLiveCallRouteImport.update({
  id: '/live-call',
  path: '/live-call',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppForgeRoute = AppForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugRoute = AppDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCveRoute = AppCveRouteImport.update({
  id: '/cve',
  path: '/cve',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesRoute = AppCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdaptersRoute = AppAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeAliasesRoute = AppKnowledgeAliasesRouteImport.update({
  id: '/knowledge_/aliases',
  path: '/knowledge/aliases',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/adapters': typeof AppAdaptersRoute
  '/agents': typeof AppAgentsRoute
  '/approvals': typeof AppApprovalsRoute
  '/capabilities': typeof AppCapabilitiesRoute
  '/chat': typeof AppChatRoute
  '/cve': typeof AppCveRoute
  '/dashboard': typeof AppDashboardRoute
  '/debug': typeof AppDebugRoute
  '/forge': typeof AppForgeRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/live-call': typeof AppLiveCallRoute
  '/mcp': typeof AppMcpRoute
  '/meta-forge': typeof AppMetaForgeRoute
  '/middleware': typeof AppMiddlewareRoute
  '/models': typeof AppModelsRoute
  '/orchestration': typeof AppOrchestrationRoute
  '/planner': typeof AppPlannerRoute
  '/policies': typeof AppPoliciesRoute
  '/python': typeof AppPythonRoute
  '/reports': typeof AppReportsRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/system-engine': typeof AppSystemEngineRoute
  '/targets': typeof AppTargetsRoute
  '/telemetry': typeof AppTelemetryRoute
  '/templates': typeof AppTemplatesRoute
  '/tools': typeof AppToolsRoute
  '/users': typeof AppUsersRoute
  '/workflows': typeof AppWorkflowsRoute
  '/knowledge/aliases': typeof AppKnowledgeAliasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/adapters': typeof AppAdaptersRoute
  '/agents': typeof AppAgentsRoute
  '/approvals': typeof AppApprovalsRoute
  '/capabilities': typeof AppCapabilitiesRoute
  '/chat': typeof AppChatRoute
  '/cve': typeof AppCveRoute
  '/dashboard': typeof AppDashboardRoute
  '/debug': typeof AppDebugRoute
  '/forge': typeof AppForgeRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/live-call': typeof AppLiveCallRoute
  '/mcp': typeof AppMcpRoute
  '/meta-forge': typeof AppMetaForgeRoute
  '/middleware': typeof AppMiddlewareRoute
  '/models': typeof AppModelsRoute
  '/orchestration': typeof AppOrchestrationRoute
  '/planner': typeof AppPlannerRoute
  '/policies': typeof AppPoliciesRoute
  '/python': typeof AppPythonRoute
  '/reports': typeof AppReportsRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/system-engine': typeof AppSystemEngineRoute
  '/targets': typeof AppTargetsRoute
  '/telemetry': typeof AppTelemetryRoute
  '/templates': typeof AppTemplatesRoute
  '/tools': typeof AppToolsRoute
  '/users': typeof AppUsersRoute
  '/workflows': typeof AppWorkflowsRoute
  '/knowledge/aliases': typeof AppKnowledgeAliasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/adapters': typeof AppAdaptersRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/capabilities': typeof AppCapabilitiesRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/cve': typeof AppCveRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debug': typeof AppDebugRoute
  '/_app/forge': typeof AppForgeRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/live-call': typeof AppLiveCallRoute
  '/_app/mcp': typeof AppMcpRoute
  '/_app/meta-forge': typeof AppMetaForgeRoute
  '/_app/middleware': typeof AppMiddlewareRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/orchestration': typeof AppOrchestrationRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/policies': typeof AppPoliciesRoute
  '/_app/python': typeof AppPythonRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/system-engine': typeof AppSystemEngineRoute
  '/_app/targets': typeof AppTargetsRoute
  '/_app/telemetry': typeof AppTelemetryRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/tools': typeof AppToolsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_app/knowledge_/aliases': typeof AppKnowledgeAliasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/adapters'
    | '/agents'
    | '/approvals'
    | '/capabilities'
    | '/chat'
    | '/cve'
    | '/dashboard'
    | '/debug'
    | '/forge'
    | '/knowledge'
    | '/live-call'
    | '/mcp'
    | '/meta-forge'
    | '/middleware'
    | '/models'
    | '/orchestration'
    | '/planner'
    | '/policies'
    | '/python'
    | '/reports'
    | '/security'
    | '/settings'
    | '/skills'
    | '/system-engine'
    | '/targets'
    | '/telemetry'
    | '/templates'
    | '/tools'
    | '/users'
    | '/workflows'
    | '/knowledge/aliases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/adapters'
    | '/agents'
    | '/approvals'
    | '/capabilities'
    | '/chat'
    | '/cve'
    | '/dashboard'
    | '/debug'
    | '/forge'
    | '/knowledge'
    | '/live-call'
    | '/mcp'
    | '/meta-forge'
    | '/middleware'
    | '/models'
    | '/orchestration'
    | '/planner'
    | '/policies'
    | '/python'
    | '/reports'
    | '/security'
    | '/settings'
    | '/skills'
    | '/system-engine'
    | '/targets'
    | '/telemetry'
    | '/templates'
    | '/tools'
    | '/users'
    | '/workflows'
    | '/knowledge/aliases'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/adapters'
    | '/_app/agents'
    | '/_app/approvals'
    | '/_app/capabilities'
    | '/_app/chat'
    | '/_app/cve'
    | '/_app/dashboard'
    | '/_app/debug'
    | '/_app/forge'
    | '/_app/knowledge'
    | '/_app/live-call'
    | '/_app/mcp'
    | '/_app/meta-forge'
    | '/_app/middleware'
    | '/_app/models'
    | '/_app/orchestration'
    | '/_app/planner'
    | '/_app/policies'
    | '/_app/python'
    | '/_app/reports'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/system-engine'
    | '/_app/targets'
    | '/_app/telemetry'
    | '/_app/templates'
    | '/_app/tools'
    | '/_app/users'
    | '/_app/workflows'
    | '/_app/knowledge_/aliases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telemetry': {
      id: '/_app/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof AppTelemetryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/targets': {
      id: '/_app/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AppTargetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-engine': {
      id: '/_app/system-engine'
      path: '/system-engine'
      fullPath: '/system-engine'
      preLoaderRoute: typeof AppSystemEngineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/python': {
      id: '/_app/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof AppPythonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orchestration': {
      id: '/_app/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof AppOrchestrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/middleware': {
      id: '/_app/middleware'
      path: '/middleware'
      fullPath: '/middleware'
      preLoaderRoute: typeof AppMiddlewareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meta-forge': {
      id: '/_app/meta-forge'
      path: '/meta-forge'
      fullPath: '/meta-forge'
      preLoaderRoute: typeof AppMetaForgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp': {
      id: '/_app/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-call': {
      id: '/_app/live-call'
      path: '/live-call'
      fullPath: '/live-call'
      preLoaderRoute: typeof AppLiveCallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forge': {
      id: '/_app/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof AppForgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cve': {
      id: '/_app/cve'
      path: '/cve'
      fullPath: '/cve'
      preLoaderRoute: typeof AppCveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities': {
      id: '/_app/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof AppCapabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adapters': {
      id: '/_app/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AppAdaptersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge_/aliases': {
      id: '/_app/knowledge_/aliases'
      path: '/knowledge/aliases'
      fullPath: '/knowledge/aliases'
      preLoaderRoute: typeof AppKnowledgeAliasesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdaptersRoute: typeof AppAdaptersRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppCapabilitiesRoute: typeof AppCapabilitiesRoute
  AppChatRoute: typeof AppChatRoute
  AppCveRoute: typeof AppCveRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebugRoute: typeof AppDebugRoute
  AppForgeRoute: typeof AppForgeRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLiveCallRoute: typeof AppLiveCallRoute
  AppMcpRoute: typeof AppMcpRoute
  AppMetaForgeRoute: typeof AppMetaForgeRoute
  AppMiddlewareRoute: typeof AppMiddlewareRoute
  AppModelsRoute: typeof AppModelsRoute
  AppOrchestrationRoute: typeof AppOrchestrationRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppPythonRoute: typeof AppPythonRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppSystemEngineRoute: typeof AppSystemEngineRoute
  AppTargetsRoute: typeof AppTargetsRoute
  AppTelemetryRoute: typeof AppTelemetryRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppToolsRoute: typeof AppToolsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppKnowledgeAliasesRoute: typeof AppKnowledgeAliasesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdaptersRoute: AppAdaptersRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppCapabilitiesRoute: AppCapabilitiesRoute,
  AppChatRoute: AppChatRoute,
  AppCveRoute: AppCveRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebugRoute: AppDebugRoute,
  AppForgeRoute: AppForgeRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLiveCallRoute: AppLiveCallRoute,
  AppMcpRoute: AppMcpRoute,
  AppMetaForgeRoute: AppMetaForgeRoute,
  AppMiddlewareRoute: AppMiddlewareRoute,
  AppModelsRoute: AppModelsRoute,
  AppOrchestrationRoute: AppOrchestrationRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppPythonRoute: AppPythonRoute,
  AppReportsRoute: AppReportsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppSystemEngineRoute: AppSystemEngineRoute,
  AppTargetsRoute: AppTargetsRoute,
  AppTelemetryRoute: AppTelemetryRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppToolsRoute: AppToolsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppKnowledgeAliasesRoute: AppKnowledgeAliasesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
