// Lightweight emoji shortcode → unicode (no library). Covers common chat picks.
// Markdown rendered through ReactMarkdown will display unicode natively (system font).

export const EMOJI_GROUPS: { label: string; emojis: { e: string; name: string }[] }[] = [
  { label: "Smileys", emojis: [
    { e: "😀", name: "grinning" }, { e: "😃", name: "smiley" }, { e: "😄", name: "smile" },
    { e: "😁", name: "grin" }, { e: "😆", name: "laughing" }, { e: "😅", name: "sweat_smile" },
    { e: "😂", name: "joy" }, { e: "🤣", name: "rofl" }, { e: "😊", name: "blush" },
    { e: "🙂", name: "slight_smile" }, { e: "🙃", name: "upside_down" }, { e: "😉", name: "wink" },
    { e: "😍", name: "heart_eyes" }, { e: "🥰", name: "smiling_hearts" }, { e: "😘", name: "kiss" },
    { e: "😎", name: "sunglasses" }, { e: "🤩", name: "star_struck" }, { e: "🥳", name: "party" },
    { e: "🤔", name: "thinking" }, { e: "🤨", name: "raised_eyebrow" }, { e: "😐", name: "neutral" },
    { e: "😑", name: "expressionless" }, { e: "😶", name: "no_mouth" }, { e: "🙄", name: "roll_eyes" },
    { e: "😏", name: "smirk" }, { e: "😒", name: "unamused" }, { e: "😞", name: "disappointed" },
    { e: "😔", name: "pensive" }, { e: "😟", name: "worried" }, { e: "😕", name: "confused" },
    { e: "🙁", name: "slight_frown" }, { e: "☹️", name: "frown" }, { e: "😣", name: "persevere" },
    { e: "😖", name: "confounded" }, { e: "😫", name: "tired" }, { e: "😩", name: "weary" },
    { e: "🥺", name: "pleading" }, { e: "😢", name: "cry" }, { e: "😭", name: "sob" },
    { e: "😤", name: "triumph" }, { e: "😠", name: "angry" }, { e: "😡", name: "rage" },
    { e: "🤬", name: "cursing" }, { e: "🤯", name: "exploding" }, { e: "😱", name: "scream" },
    { e: "😨", name: "fearful" }, { e: "😰", name: "anxious" }, { e: "😥", name: "sad_relieved" },
    { e: "😓", name: "sweat" }, { e: "🤗", name: "hug" }, { e: "🤭", name: "hand_mouth" },
    { e: "🤫", name: "shush" }, { e: "🤥", name: "lying" }, { e: "😶‍🌫️", name: "fog_face" },
    { e: "😴", name: "sleeping" }, { e: "😪", name: "sleepy" }, { e: "🤤", name: "drooling" },
    { e: "😋", name: "yum" }, { e: "🤓", name: "nerd" }, { e: "🧐", name: "monocle" },
    { e: "🤠", name: "cowboy" }, { e: "🤡", name: "clown" }, { e: "👻", name: "ghost" },
    { e: "💀", name: "skull" }, { e: "☠️", name: "skull_bones" }, { e: "👽", name: "alien" },
    { e: "🤖", name: "robot" }, { e: "🥷", name: "ninja" }, { e: "👀", name: "eyes" },
  ]},
  { label: "Symbols", emojis: [
    { e: "✅", name: "check" }, { e: "✔️", name: "checkmark" }, { e: "❌", name: "x" },
    { e: "❎", name: "negative_check" }, { e: "⛔", name: "no_entry" }, { e: "🚫", name: "prohibited" },
    { e: "⚠️", name: "warning" }, { e: "❗", name: "exclamation" }, { e: "❓", name: "question" },
    { e: "‼️", name: "double_exclamation" }, { e: "⁉️", name: "interrobang" },
    { e: "🔒", name: "lock" }, { e: "🔓", name: "unlock" }, { e: "🔐", name: "lock_key" },
    { e: "🔑", name: "key" }, { e: "🗝️", name: "old_key" }, { e: "🛡️", name: "shield" },
    { e: "💡", name: "bulb" }, { e: "⭐", name: "star" }, { e: "🌟", name: "glow_star" },
    { e: "🔥", name: "fire" }, { e: "✨", name: "sparkles" }, { e: "💎", name: "gem" },
    { e: "💯", name: "hundred" }, { e: "💢", name: "anger" }, { e: "💥", name: "boom" },
    { e: "💫", name: "dizzy" }, { e: "💦", name: "sweat_drops" }, { e: "💨", name: "dash" },
    { e: "🕐", name: "clock" }, { e: "⏰", name: "alarm" }, { e: "⏳", name: "hourglass_flow" },
    { e: "⌛", name: "hourglass" }, { e: "♻️", name: "recycle" }, { e: "🔱", name: "trident" },
  ]},
  { label: "Tech", emojis: [
    { e: "💻", name: "laptop" }, { e: "🖥️", name: "desktop" }, { e: "⌨️", name: "keyboard" },
    { e: "🖱️", name: "mouse" }, { e: "🖨️", name: "printer" }, { e: "📱", name: "phone" },
    { e: "📞", name: "telephone" }, { e: "☎️", name: "phone_old" }, { e: "📡", name: "satellite" },
    { e: "🛰️", name: "satellite_orbit" }, { e: "📶", name: "signal" }, { e: "📲", name: "phone_arrow" },
    { e: "🔋", name: "battery" }, { e: "🔌", name: "plug" }, { e: "💾", name: "floppy" },
    { e: "💿", name: "cd" }, { e: "📀", name: "dvd" }, { e: "💽", name: "minidisc" },
    { e: "🎯", name: "target" }, { e: "📊", name: "chart" }, { e: "📈", name: "chart_up" },
    { e: "📉", name: "chart_down" }, { e: "🧠", name: "brain" }, { e: "⚙️", name: "gear" },
    { e: "🔧", name: "wrench" }, { e: "🔨", name: "hammer" }, { e: "🛠️", name: "tools" },
    { e: "⚡", name: "zap" }, { e: "🔩", name: "bolt" }, { e: "🐛", name: "bug" },
    { e: "🚀", name: "rocket" }, { e: "🦅", name: "eagle" }, { e: "🛸", name: "ufo" },
    { e: "🧬", name: "dna" }, { e: "🔬", name: "microscope" }, { e: "🔭", name: "telescope" },
    { e: "📷", name: "camera" }, { e: "📸", name: "camera_flash" }, { e: "🎥", name: "movie_camera" },
    { e: "🎙️", name: "studio_mic" }, { e: "🎤", name: "mic" }, { e: "🔊", name: "speaker" },
    { e: "🔇", name: "mute" }, { e: "📻", name: "radio" }, { e: "🎮", name: "game" },
  ]},
  { label: "Hearts & Hands", emojis: [
    { e: "❤️", name: "heart" }, { e: "🧡", name: "orange_heart" }, { e: "💛", name: "yellow_heart" },
    { e: "💚", name: "green_heart" }, { e: "💙", name: "blue_heart" }, { e: "💜", name: "purple_heart" },
    { e: "🖤", name: "black_heart" }, { e: "🤍", name: "white_heart" }, { e: "🤎", name: "brown_heart" },
    { e: "💔", name: "broken_heart" }, { e: "❣️", name: "heart_excl" }, { e: "💕", name: "two_hearts" },
    { e: "💞", name: "revolving_hearts" }, { e: "💓", name: "beating_heart" }, { e: "💗", name: "growing_heart" },
    { e: "💖", name: "sparkling_heart" }, { e: "💘", name: "cupid" }, { e: "💝", name: "gift_heart" },
    { e: "👍", name: "thumbsup" }, { e: "👎", name: "thumbsdown" }, { e: "👊", name: "fist" },
    { e: "✊", name: "raised_fist" }, { e: "🤛", name: "left_fist" }, { e: "🤜", name: "right_fist" },
    { e: "👏", name: "clap" }, { e: "🙌", name: "raised_hands" }, { e: "👐", name: "open_hands" },
    { e: "🤲", name: "palms_up" }, { e: "🙏", name: "pray" }, { e: "🤝", name: "handshake" },
    { e: "💪", name: "muscle" }, { e: "🦾", name: "mechanical_arm" }, { e: "🫡", name: "salute" },
    { e: "👋", name: "wave" }, { e: "🤚", name: "raised_back_hand" }, { e: "✋", name: "raised_hand" },
    { e: "🖐️", name: "hand_fingers" }, { e: "👌", name: "ok_hand" }, { e: "🤌", name: "pinched" },
    { e: "🤏", name: "pinching" }, { e: "✌️", name: "victory" }, { e: "🤞", name: "crossed_fingers" },
    { e: "🤟", name: "love_you" }, { e: "🤘", name: "rock_on" }, { e: "👈", name: "point_left" },
    { e: "👉", name: "point_right" }, { e: "👆", name: "point_up" }, { e: "👇", name: "point_down" },
  ]},
  { label: "Nature & Food", emojis: [
    { e: "🌞", name: "sun" }, { e: "🌝", name: "moon_face" }, { e: "🌚", name: "new_moon_face" },
    { e: "🌙", name: "moon" }, { e: "⭐", name: "star_n" }, { e: "🌈", name: "rainbow" },
    { e: "☁️", name: "cloud" }, { e: "⛅", name: "partly_sunny" }, { e: "🌧️", name: "rain" },
    { e: "⛈️", name: "thunder" }, { e: "❄️", name: "snowflake" }, { e: "🌊", name: "wave_water" },
    { e: "🌍", name: "earth" }, { e: "🌎", name: "earth_americas" }, { e: "🌏", name: "earth_asia" },
    { e: "🌹", name: "rose" }, { e: "🌷", name: "tulip" }, { e: "🌻", name: "sunflower" },
    { e: "🍀", name: "clover" }, { e: "🌳", name: "tree" }, { e: "🌲", name: "evergreen" },
    { e: "🍎", name: "apple" }, { e: "🍕", name: "pizza" }, { e: "🍔", name: "burger" },
    { e: "🍟", name: "fries" }, { e: "🌮", name: "taco" }, { e: "🍣", name: "sushi" },
    { e: "🍩", name: "donut" }, { e: "🍪", name: "cookie" }, { e: "🎂", name: "cake" },
    { e: "🍰", name: "shortcake" }, { e: "🍫", name: "chocolate" }, { e: "☕", name: "coffee" },
    { e: "🍵", name: "tea" }, { e: "🍺", name: "beer" }, { e: "🍷", name: "wine" },
    { e: "🥂", name: "champagne" }, { e: "🍾", name: "bottle" },
  ]},
  { label: "Activities & Flags", emojis: [
    { e: "🎉", name: "tada" }, { e: "🎊", name: "confetti" }, { e: "🎁", name: "gift" },
    { e: "🏆", name: "trophy" }, { e: "🥇", name: "first" }, { e: "🥈", name: "second" },
    { e: "🥉", name: "third" }, { e: "🎖️", name: "medal" }, { e: "🏅", name: "sport_medal" },
    { e: "⚽", name: "soccer" }, { e: "🏀", name: "basketball" }, { e: "🏈", name: "football" },
    { e: "⚾", name: "baseball" }, { e: "🎾", name: "tennis" }, { e: "🏐", name: "volleyball" },
    { e: "🎱", name: "8ball" }, { e: "🎮", name: "videogame" }, { e: "🎲", name: "dice" },
    { e: "♟️", name: "chess" }, { e: "🎭", name: "theater" }, { e: "🎨", name: "art" },
    { e: "🎬", name: "clapper" }, { e: "🎵", name: "music" }, { e: "🎶", name: "notes" },
    { e: "🇹🇷", name: "tr" }, { e: "🇺🇸", name: "us" }, { e: "🇬🇧", name: "gb" },
    { e: "🇩🇪", name: "de" }, { e: "🇫🇷", name: "fr" }, { e: "🇯🇵", name: "jp" },
    { e: "🇨🇳", name: "cn" }, { e: "🇰🇷", name: "kr" }, { e: "🇷🇺", name: "ru" },
    { e: "🇮🇹", name: "it" }, { e: "🇪🇸", name: "es" }, { e: "🇧🇷", name: "br" },
    { e: "🏳️", name: "white_flag" }, { e: "🏴", name: "black_flag" }, { e: "🏁", name: "checkered" },
    { e: "🚩", name: "triangular_flag" }, { e: "🏳️‍🌈", name: "rainbow_flag" },
  ]},
  { label: "Animals", emojis: [
    { e: "🐶", name: "dog" }, { e: "🐱", name: "cat" }, { e: "🦊", name: "fox" },
    { e: "🐺", name: "wolf" }, { e: "🦁", name: "lion" }, { e: "🐯", name: "tiger" },
    { e: "🐻", name: "bear" }, { e: "🐼", name: "panda" }, { e: "🐨", name: "koala" },
    { e: "🐮", name: "cow" }, { e: "🐷", name: "pig" }, { e: "🐸", name: "frog" },
    { e: "🐵", name: "monkey" }, { e: "🙈", name: "see_no_evil" }, { e: "🙉", name: "hear_no_evil" },
    { e: "🙊", name: "speak_no_evil" }, { e: "🐒", name: "monkey_full" }, { e: "🦍", name: "gorilla" },
    { e: "🐔", name: "chicken" }, { e: "🐧", name: "penguin" }, { e: "🐦", name: "bird" },
    { e: "🦉", name: "owl" }, { e: "🦄", name: "unicorn" }, { e: "🐝", name: "bee" },
    { e: "🦋", name: "butterfly" }, { e: "🐢", name: "turtle" }, { e: "🐍", name: "snake" },
    { e: "🦖", name: "trex" }, { e: "🐙", name: "octopus" }, { e: "🦑", name: "squid" },
    { e: "🦀", name: "crab" }, { e: "🐠", name: "fish_tropical" }, { e: "🐬", name: "dolphin" },
    { e: "🐳", name: "whale" }, { e: "🦈", name: "shark" }, { e: "🐊", name: "croc" },
    { e: "🦓", name: "zebra" }, { e: "🦒", name: "giraffe" }, { e: "🐘", name: "elephant" },
    { e: "🦏", name: "rhino" }, { e: "🐪", name: "camel" }, { e: "🐎", name: "horse" },
  ]},
  { label: "Travel & Places", emojis: [
    { e: "🚗", name: "car" }, { e: "🚕", name: "taxi" }, { e: "🚙", name: "suv" },
    { e: "🚌", name: "bus" }, { e: "🚎", name: "trolleybus" }, { e: "🏎️", name: "racing_car" },
    { e: "🚓", name: "police_car" }, { e: "🚑", name: "ambulance" }, { e: "🚒", name: "fire_engine" },
    { e: "🚐", name: "minibus" }, { e: "🛻", name: "pickup" }, { e: "🚚", name: "truck" },
    { e: "🚛", name: "lorry" }, { e: "🚜", name: "tractor" }, { e: "🛵", name: "scooter" },
    { e: "🏍️", name: "motorcycle" }, { e: "🚲", name: "bike" }, { e: "🛴", name: "kick_scooter" },
    { e: "✈️", name: "plane" }, { e: "🛩️", name: "small_plane" }, { e: "🚁", name: "helicopter" },
    { e: "🚀", name: "rocket_t" }, { e: "🛸", name: "ufo_t" }, { e: "🚢", name: "ship" },
    { e: "⛵", name: "sailboat" }, { e: "🛥️", name: "motor_boat" }, { e: "🚤", name: "speedboat" },
    { e: "⚓", name: "anchor" }, { e: "🚂", name: "locomotive" }, { e: "🚆", name: "train" },
    { e: "🚇", name: "metro" }, { e: "🚉", name: "station" }, { e: "🏠", name: "house" },
    { e: "🏡", name: "home" }, { e: "🏢", name: "office" }, { e: "🏬", name: "department" },
    { e: "🏥", name: "hospital" }, { e: "🏦", name: "bank" }, { e: "🏨", name: "hotel" },
    { e: "🏰", name: "castle" }, { e: "🗽", name: "statue_liberty" }, { e: "🗼", name: "tokyo_tower" },
    { e: "🗿", name: "moai" }, { e: "🏝️", name: "island" }, { e: "🏔️", name: "mountain" },
    { e: "🌋", name: "volcano" }, { e: "🏖️", name: "beach" }, { e: "🌃", name: "night_city" },
    { e: "🌆", name: "cityscape" }, { e: "🌇", name: "sunset_city" }, { e: "🌉", name: "bridge_night" },
  ]},
];

const SHORTCODE_MAP: Record<string, string> = (() => {
  const m: Record<string, string> = {};
  for (const g of EMOJI_GROUPS) for (const it of g.emojis) m[it.name] = it.e;
  return m;
})();

/** Replace :shortcode: with unicode emoji inside a markdown string. */
export function expandEmojiShortcodes(src: string): string {
  return src.replace(/:([a-z0-9_+-]+):/gi, (m, name) => SHORTCODE_MAP[name.toLowerCase()] ?? m);
}
