#!/usr/bin/env python3
# @tool: ssl-report-generator
# @description: Formats SSL probe results into a professional Markdown report
# @args: {"probe_results": "object"}
import sys, json

def main():
    try:
        input_data = json.loads(sys.stdin.read())
        res = input_data.get('probe_results', {})
        
        domain = res.get('domain', 'Unknown')
        expiry = res.get('expiry_date', 'Unknown')
        days = res.get('days_remaining', 'Unknown')
        status = res.get('status', 'Unknown').upper()
        
        emoji = '🔴' if status == 'CRITICAL' else '🟢'
        
        report = f"## {emoji} SSL Certificate Status: {domain}\n\n| Metric | Value |\n| :--- | :--- |\n| **Status** | {emoji} {status} |\n| **Expiry Date** | {expiry} |\n| **Days Remaining** | {days} |\n\n*Generated by ELARA SSL Monitor*"
        
        print(json.dumps({"markdown_report": report}))
    except Exception as e:
        print(json.dumps({"error": str(e)}))

if __name__ == '__main__':
    main()