/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MailRouteImport } from './routes/mail'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MetaForgeRouteImport } from './routes/meta-forge'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as RagDocumentsRouteImport } from './routes/rag-documents'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SiemRouteImport } from './routes/siem'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as TelemetrySourcesRouteImport } from './routes/telemetry-sources'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as VisionAudioRouteImport } from './routes/vision-audio'
import { Route as ReportingCostRouteImport } from './routes/reporting.cost'
import { Route as ReportingExportsRouteImport } from './routes/reporting.exports'
import { Route as ReportingOverviewRouteImport } from './routes/reporting.overview'
import { Route as ReportingRagRouteImport } from './routes/reporting.rag'
import { Route as ReportingUsageRouteImport } from './routes/reporting.usage'
import { Route as ReportingUsersRouteImport } from './routes/reporting.users'
import { Route as WSectionCardRouteImport } from './routes/w.$section.$card'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaForgeRoute = MetaForgeRouteImport.update({
  id: '/meta-forge',
  path: '/meta-forge',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RagDocumentsRoute = RagDocumentsRouteImport.update({
  id: '/rag-documents',
  path: '/rag-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiemRoute = SiemRouteImport.update({
  id: '/siem',
  path: '/siem',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetrySourcesRoute = TelemetrySourcesRouteImport.update({
  id: '/telemetry-sources',
  path: '/telemetry-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionAudioRoute = VisionAudioRouteImport.update({
  id: '/vision-audio',
  path: '/vision-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingCostRoute = ReportingCostRouteImport.update({
  id: '/reporting/cost',
  path: '/reporting/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingExportsRoute = ReportingExportsRouteImport.update({
  id: '/reporting/exports',
  path: '/reporting/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingOverviewRoute = ReportingOverviewRouteImport.update({
  id: '/reporting/overview',
  path: '/reporting/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRagRoute = ReportingRagRouteImport.update({
  id: '/reporting/rag',
  path: '/reporting/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingUsageRoute = ReportingUsageRouteImport.update({
  id: '/reporting/usage',
  path: '/reporting/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingUsersRoute = ReportingUsersRouteImport.update({
  id: '/reporting/users',
  path: '/reporting/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WSectionCardRoute = WSectionCardRouteImport.update({
  id: '/w/$section/$card',
  path: '/w/$section/$card',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/adapters': typeof AdaptersRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/authentication': typeof AuthenticationRoute
  '/backup': typeof BackupRoute
  '/capabilities': typeof CapabilitiesRoute
  '/certificates': typeof CertificatesRoute
  '/converter': typeof ConverterRoute
  '/engine': typeof EngineRoute
  '/factory': typeof FactoryRoute
  '/fleet': typeof FleetRoute
  '/flows': typeof FlowsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/meta-forge': typeof MetaForgeRoute
  '/models': typeof ModelsRoute
  '/orchestration': typeof OrchestrationRoute
  '/planner': typeof PlannerRoute
  '/policy': typeof PolicyRoute
  '/rag-documents': typeof RagDocumentsRoute
  '/rbac': typeof RbacRoute
  '/registry': typeof RegistryRoute
  '/runtime': typeof RuntimeRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/targets': typeof TargetsRoute
  '/telemetry-sources': typeof TelemetrySourcesRoute
  '/theme': typeof ThemeRoute
  '/tools': typeof ToolsRoute
  '/users': typeof UsersRoute
  '/vision': typeof VisionRoute
  '/vision-audio': typeof VisionAudioRoute
  '/reporting/cost': typeof ReportingCostRoute
  '/reporting/exports': typeof ReportingExportsRoute
  '/reporting/overview': typeof ReportingOverviewRoute
  '/reporting/rag': typeof ReportingRagRoute
  '/reporting/usage': typeof ReportingUsageRoute
  '/reporting/users': typeof ReportingUsersRoute
  '/w/$section/$card': typeof WSectionCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/adapters': typeof AdaptersRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/authentication': typeof AuthenticationRoute
  '/backup': typeof BackupRoute
  '/capabilities': typeof CapabilitiesRoute
  '/certificates': typeof CertificatesRoute
  '/converter': typeof ConverterRoute
  '/engine': typeof EngineRoute
  '/factory': typeof FactoryRoute
  '/fleet': typeof FleetRoute
  '/flows': typeof FlowsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/meta-forge': typeof MetaForgeRoute
  '/models': typeof ModelsRoute
  '/orchestration': typeof OrchestrationRoute
  '/planner': typeof PlannerRoute
  '/policy': typeof PolicyRoute
  '/rag-documents': typeof RagDocumentsRoute
  '/rbac': typeof RbacRoute
  '/registry': typeof RegistryRoute
  '/runtime': typeof RuntimeRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/targets': typeof TargetsRoute
  '/telemetry-sources': typeof TelemetrySourcesRoute
  '/theme': typeof ThemeRoute
  '/tools': typeof ToolsRoute
  '/users': typeof UsersRoute
  '/vision': typeof VisionRoute
  '/vision-audio': typeof VisionAudioRoute
  '/reporting/cost': typeof ReportingCostRoute
  '/reporting/exports': typeof ReportingExportsRoute
  '/reporting/overview': typeof ReportingOverviewRoute
  '/reporting/rag': typeof ReportingRagRoute
  '/reporting/usage': typeof ReportingUsageRoute
  '/reporting/users': typeof ReportingUsersRoute
  '/w/$section/$card': typeof WSectionCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/adapters': typeof AdaptersRoute
  '/agents': typeof AgentsRoute
  '/approvals': typeof ApprovalsRoute
  '/authentication': typeof AuthenticationRoute
  '/backup': typeof BackupRoute
  '/capabilities': typeof CapabilitiesRoute
  '/certificates': typeof CertificatesRoute
  '/converter': typeof ConverterRoute
  '/engine': typeof EngineRoute
  '/factory': typeof FactoryRoute
  '/fleet': typeof FleetRoute
  '/flows': typeof FlowsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/meta-forge': typeof MetaForgeRoute
  '/models': typeof ModelsRoute
  '/orchestration': typeof OrchestrationRoute
  '/planner': typeof PlannerRoute
  '/policy': typeof PolicyRoute
  '/rag-documents': typeof RagDocumentsRoute
  '/rbac': typeof RbacRoute
  '/registry': typeof RegistryRoute
  '/runtime': typeof RuntimeRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/targets': typeof TargetsRoute
  '/telemetry-sources': typeof TelemetrySourcesRoute
  '/theme': typeof ThemeRoute
  '/tools': typeof ToolsRoute
  '/users': typeof UsersRoute
  '/vision': typeof VisionRoute
  '/vision-audio': typeof VisionAudioRoute
  '/reporting/cost': typeof ReportingCostRoute
  '/reporting/exports': typeof ReportingExportsRoute
  '/reporting/overview': typeof ReportingOverviewRoute
  '/reporting/rag': typeof ReportingRagRoute
  '/reporting/usage': typeof ReportingUsageRoute
  '/reporting/users': typeof ReportingUsersRoute
  '/w/$section/$card': typeof WSectionCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/adapters'
    | '/agents'
    | '/approvals'
    | '/authentication'
    | '/backup'
    | '/capabilities'
    | '/certificates'
    | '/converter'
    | '/engine'
    | '/factory'
    | '/fleet'
    | '/flows'
    | '/knowledge'
    | '/login'
    | '/mail'
    | '/mcp'
    | '/memory'
    | '/meta-forge'
    | '/models'
    | '/orchestration'
    | '/planner'
    | '/policy'
    | '/rag-documents'
    | '/rbac'
    | '/registry'
    | '/runtime'
    | '/security'
    | '/services'
    | '/settings'
    | '/siem'
    | '/skills'
    | '/system'
    | '/targets'
    | '/telemetry-sources'
    | '/theme'
    | '/tools'
    | '/users'
    | '/vision'
    | '/vision-audio'
    | '/reporting/cost'
    | '/reporting/exports'
    | '/reporting/overview'
    | '/reporting/rag'
    | '/reporting/usage'
    | '/reporting/users'
    | '/w/$section/$card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/adapters'
    | '/agents'
    | '/approvals'
    | '/authentication'
    | '/backup'
    | '/capabilities'
    | '/certificates'
    | '/converter'
    | '/engine'
    | '/factory'
    | '/fleet'
    | '/flows'
    | '/knowledge'
    | '/login'
    | '/mail'
    | '/mcp'
    | '/memory'
    | '/meta-forge'
    | '/models'
    | '/orchestration'
    | '/planner'
    | '/policy'
    | '/rag-documents'
    | '/rbac'
    | '/registry'
    | '/runtime'
    | '/security'
    | '/services'
    | '/settings'
    | '/siem'
    | '/skills'
    | '/system'
    | '/targets'
    | '/telemetry-sources'
    | '/theme'
    | '/tools'
    | '/users'
    | '/vision'
    | '/vision-audio'
    | '/reporting/cost'
    | '/reporting/exports'
    | '/reporting/overview'
    | '/reporting/rag'
    | '/reporting/usage'
    | '/reporting/users'
    | '/w/$section/$card'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/adapters'
    | '/agents'
    | '/approvals'
    | '/authentication'
    | '/backup'
    | '/capabilities'
    | '/certificates'
    | '/converter'
    | '/engine'
    | '/factory'
    | '/fleet'
    | '/flows'
    | '/knowledge'
    | '/login'
    | '/mail'
    | '/mcp'
    | '/memory'
    | '/meta-forge'
    | '/models'
    | '/orchestration'
    | '/planner'
    | '/policy'
    | '/rag-documents'
    | '/rbac'
    | '/registry'
    | '/runtime'
    | '/security'
    | '/services'
    | '/settings'
    | '/siem'
    | '/skills'
    | '/system'
    | '/targets'
    | '/telemetry-sources'
    | '/theme'
    | '/tools'
    | '/users'
    | '/vision'
    | '/vision-audio'
    | '/reporting/cost'
    | '/reporting/exports'
    | '/reporting/overview'
    | '/reporting/rag'
    | '/reporting/usage'
    | '/reporting/users'
    | '/w/$section/$card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdaptersRoute: typeof AdaptersRoute
  AgentsRoute: typeof AgentsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuthenticationRoute: typeof AuthenticationRoute
  BackupRoute: typeof BackupRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CertificatesRoute: typeof CertificatesRoute
  ConverterRoute: typeof ConverterRoute
  EngineRoute: typeof EngineRoute
  FactoryRoute: typeof FactoryRoute
  FleetRoute: typeof FleetRoute
  FlowsRoute: typeof FlowsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRoute
  McpRoute: typeof McpRoute
  MemoryRoute: typeof MemoryRoute
  MetaForgeRoute: typeof MetaForgeRoute
  ModelsRoute: typeof ModelsRoute
  OrchestrationRoute: typeof OrchestrationRoute
  PlannerRoute: typeof PlannerRoute
  PolicyRoute: typeof PolicyRoute
  RagDocumentsRoute: typeof RagDocumentsRoute
  RbacRoute: typeof RbacRoute
  RegistryRoute: typeof RegistryRoute
  RuntimeRoute: typeof RuntimeRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SiemRoute: typeof SiemRoute
  SkillsRoute: typeof SkillsRoute
  SystemRoute: typeof SystemRoute
  TargetsRoute: typeof TargetsRoute
  TelemetrySourcesRoute: typeof TelemetrySourcesRoute
  ThemeRoute: typeof ThemeRoute
  ToolsRoute: typeof ToolsRoute
  UsersRoute: typeof UsersRoute
  VisionRoute: typeof VisionRoute
  VisionAudioRoute: typeof VisionAudioRoute
  ReportingCostRoute: typeof ReportingCostRoute
  ReportingExportsRoute: typeof ReportingExportsRoute
  ReportingOverviewRoute: typeof ReportingOverviewRoute
  ReportingRagRoute: typeof ReportingRagRoute
  ReportingUsageRoute: typeof ReportingUsageRoute
  ReportingUsersRoute: typeof ReportingUsersRoute
  WSectionCardRoute: typeof WSectionCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-forge': {
      id: '/meta-forge'
      path: '/meta-forge'
      fullPath: '/meta-forge'
      preLoaderRoute: typeof MetaForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rag-documents': {
      id: '/rag-documents'
      path: '/rag-documents'
      fullPath: '/rag-documents'
      preLoaderRoute: typeof RagDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siem': {
      id: '/siem'
      path: '/siem'
      fullPath: '/siem'
      preLoaderRoute: typeof SiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry-sources': {
      id: '/telemetry-sources'
      path: '/telemetry-sources'
      fullPath: '/telemetry-sources'
      preLoaderRoute: typeof TelemetrySourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-audio': {
      id: '/vision-audio'
      path: '/vision-audio'
      fullPath: '/vision-audio'
      preLoaderRoute: typeof VisionAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/cost': {
      id: '/reporting/cost'
      path: '/reporting/cost'
      fullPath: '/reporting/cost'
      preLoaderRoute: typeof ReportingCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/exports': {
      id: '/reporting/exports'
      path: '/reporting/exports'
      fullPath: '/reporting/exports'
      preLoaderRoute: typeof ReportingExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/overview': {
      id: '/reporting/overview'
      path: '/reporting/overview'
      fullPath: '/reporting/overview'
      preLoaderRoute: typeof ReportingOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/rag': {
      id: '/reporting/rag'
      path: '/reporting/rag'
      fullPath: '/reporting/rag'
      preLoaderRoute: typeof ReportingRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/usage': {
      id: '/reporting/usage'
      path: '/reporting/usage'
      fullPath: '/reporting/usage'
      preLoaderRoute: typeof ReportingUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/users': {
      id: '/reporting/users'
      path: '/reporting/users'
      fullPath: '/reporting/users'
      preLoaderRoute: typeof ReportingUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$section/$card': {
      id: '/w/$section/$card'
      path: '/w/$section/$card'
      fullPath: '/w/$section/$card'
      preLoaderRoute: typeof WSectionCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdaptersRoute: AdaptersRoute,
  AgentsRoute: AgentsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuthenticationRoute: AuthenticationRoute,
  BackupRoute: BackupRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CertificatesRoute: CertificatesRoute,
  ConverterRoute: ConverterRoute,
  EngineRoute: EngineRoute,
  FactoryRoute: FactoryRoute,
  FleetRoute: FleetRoute,
  FlowsRoute: FlowsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRoute,
  McpRoute: McpRoute,
  MemoryRoute: MemoryRoute,
  MetaForgeRoute: MetaForgeRoute,
  ModelsRoute: ModelsRoute,
  OrchestrationRoute: OrchestrationRoute,
  PlannerRoute: PlannerRoute,
  PolicyRoute: PolicyRoute,
  RagDocumentsRoute: RagDocumentsRoute,
  RbacRoute: RbacRoute,
  RegistryRoute: RegistryRoute,
  RuntimeRoute: RuntimeRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SiemRoute: SiemRoute,
  SkillsRoute: SkillsRoute,
  SystemRoute: SystemRoute,
  TargetsRoute: TargetsRoute,
  TelemetrySourcesRoute: TelemetrySourcesRoute,
  ThemeRoute: ThemeRoute,
  ToolsRoute: ToolsRoute,
  UsersRoute: UsersRoute,
  VisionRoute: VisionRoute,
  VisionAudioRoute: VisionAudioRoute,
  ReportingCostRoute: ReportingCostRoute,
  ReportingExportsRoute: ReportingExportsRoute,
  ReportingOverviewRoute: ReportingOverviewRoute,
  ReportingRagRoute: ReportingRagRoute,
  ReportingUsageRoute: ReportingUsageRoute,
  ReportingUsersRoute: ReportingUsersRoute,
  WSectionCardRoute: WSectionCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
